#!/usr/bin/env python3
"""
Amenthyx AI Teams — Shared PDF Activity Summary Generator
Usage: python PDF_GENERATOR.py <report_number> <project_name> [team_dir]
"""

import sys
import os
import json

sys.stdout.reconfigure(encoding='utf-8')

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from datetime import datetime


def read_file_safe(path):
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as f:
            return f.read()
    return None


def count_kanban(team_dir):
    kanban = read_file_safe(os.path.join(team_dir, "KANBAN.md"))
    if kanban:
        return {
            "done": kanban.count("[x]"),
            "in_progress": kanban.count("[~]"),
            "in_review": kanban.count("[?]"),
            "backlog": kanban.count("[ ]"),
        }
    return {"done": 0, "in_progress": 0, "in_review": 0, "backlog": 0}


def discover_artifacts(team_dir):
    artifacts = []
    if os.path.exists(team_dir):
        for root, dirs, files in os.walk(team_dir):
            for f in files:
                if f.endswith(('.md', '.yaml', '.yml', '.json', '.py', '.pptx', '.pdf')):
                    rel_path = os.path.relpath(os.path.join(root, f), team_dir)
                    artifacts.append(f".team/{rel_path}")
    return artifacts


def create_activity_pdf(report_num, project_name, activities=None, team_dir=".team"):
    reports_dir = os.path.join(team_dir, "reports")
    os.makedirs(reports_dir, exist_ok=True)
    filepath = os.path.join(reports_dir, f"activity_{report_num:03d}.pdf")

    doc = SimpleDocTemplate(filepath, pagesize=letter,
                            topMargin=0.75 * inch, bottomMargin=0.75 * inch)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle', parent=styles['Title'],
        textColor=HexColor('#1a1a2e'), fontSize=20, spaceAfter=12
    )
    heading_style = ParagraphStyle(
        'CustomHeading', parent=styles['Heading2'],
        textColor=HexColor('#00d2ff'), fontSize=14, spaceAfter=8
    )
    body_style = ParagraphStyle(
        'CustomBody', parent=styles['Normal'],
        fontSize=10, spaceAfter=6, leading=14
    )
    small_style = ParagraphStyle(
        'Small', parent=styles['Normal'],
        fontSize=8, spaceAfter=4, leading=10, textColor=HexColor('#666666')
    )

    elements = []

    # Title
    elements.append(Paragraph(f"Project Activity Summary &mdash; Report #{report_num}", title_style))
    elements.append(Paragraph(f"{project_name} | {datetime.now().strftime('%Y-%m-%d %H:%M')}", body_style))
    elements.append(Paragraph("Generated by Amenthyx AI Teams", small_style))
    elements.append(Spacer(1, 0.3 * inch))

    # Section 1: Completed Activities
    elements.append(Paragraph("1. COMPLETED ACTIVITIES", heading_style))
    if activities:
        for activity in activities:
            ts = activity.get("time", "N/A")
            agent = activity.get("agent", "Unknown")
            desc = activity.get("description", "")
            result = activity.get("result", "Done")
            elements.append(Paragraph(
                f"[{ts}] <b>{agent}</b>: {desc} &mdash; {result}", body_style
            ))
    else:
        elements.append(Paragraph("No activities recorded yet. PM will populate this as agents report progress.", body_style))

    elements.append(Spacer(1, 0.2 * inch))

    # Section 2: In-Progress Activities
    elements.append(Paragraph("2. IN-PROGRESS ACTIVITIES", heading_style))
    status_file = read_file_safe(os.path.join(team_dir, "TEAM_STATUS.md"))
    if status_file:
        for line in status_file.split('\n'):
            if line.strip():
                elements.append(Paragraph(line.strip(), body_style))
    else:
        elements.append(Paragraph("Team status not yet populated.", body_style))

    elements.append(Spacer(1, 0.2 * inch))

    # Section 3: Key Decisions
    elements.append(Paragraph("3. KEY DECISIONS MADE", heading_style))
    decisions = read_file_safe(os.path.join(team_dir, "DECISION_LOG.md"))
    if decisions:
        for line in decisions.split('\n')[:30]:
            if line.strip():
                elements.append(Paragraph(line.strip(), body_style))
    else:
        elements.append(Paragraph("No decisions logged yet.", body_style))

    elements.append(Spacer(1, 0.2 * inch))

    # Section 4: Artifacts Produced
    elements.append(Paragraph("4. ARTIFACTS PRODUCED", heading_style))
    artifacts = discover_artifacts(team_dir)
    if artifacts:
        for artifact in artifacts:
            elements.append(Paragraph(artifact, body_style))
    else:
        elements.append(Paragraph("No artifacts produced yet.", body_style))

    elements.append(Spacer(1, 0.2 * inch))

    # Section 5: Metrics
    elements.append(Paragraph("5. METRICS", heading_style))
    kanban = count_kanban(team_dir)
    total = kanban["done"] + kanban["in_progress"] + kanban["in_review"] + kanban["backlog"]
    elements.append(Paragraph(f"Tasks completed: {kanban['done']}", body_style))
    elements.append(Paragraph(f"Tasks in progress: {kanban['in_progress']}", body_style))
    elements.append(Paragraph(f"Tasks in review: {kanban['in_review']}", body_style))
    elements.append(Paragraph(f"Tasks remaining: {kanban['backlog']}", body_style))
    elements.append(Paragraph(f"Total tasks: {total}", body_style))
    if total > 0:
        elements.append(Paragraph(f"Completion: {int(kanban['done'] / total * 100)}%", body_style))

    doc.build(elements)
    print(f"PDF saved: {filepath}")
    return filepath


if __name__ == "__main__":
    report_num = int(sys.argv[1]) if len(sys.argv) > 1 else 1
    project_name = sys.argv[2] if len(sys.argv) > 2 else "Project"
    team_dir = sys.argv[3] if len(sys.argv) > 3 else ".team"

    # Try to load activities from a JSON file if provided
    activities = []
    activities_path = os.path.join(team_dir, "reports", "activities.json")
    if os.path.exists(activities_path):
        with open(activities_path, 'r', encoding='utf-8') as f:
            activities = json.load(f)
    else:
        activities = [
            {"time": datetime.now().strftime("%H:%M"), "agent": "PM",
             "description": "Project initialization", "result": "Complete"}
        ]

    create_activity_pdf(report_num, project_name, activities, team_dir)
